openapi: 3.0.1
info:
  description: This is the API documentation for the Parodos Workflow Service. It
    provides operations to execute assessments to determine infrastructure options
    (tooling + environments). Also executes infrastructure task workflows to call
    downstream systems to stand-up an infrastructure option.
  title: Parodos Workflow Service API
  version: v1.0.0
servers:
- description: Generated server url
  url: http://localhost:8080
tags:
- description: Operations about workflow
  name: Workflow
- description: Operations about project
  name: Project
- description: Operations about workflow definition
  name: Workflow Definition
paths:
  /api/v1/workflows:
    post:
      operationId: execute
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkFlowRequestDTO'
        required: true
      responses:
        "403":
          description: Forbidden
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkFlowResponseDTO'
          description: Succeeded
        "401":
          description: Unauthorized
      summary: Executes a workflow
      tags:
      - Workflow
      x-contentType: application/json
      x-accepts: application/json
  /api/v1/workflows/{workFlowExecutionId}/checkers/{workFlowCheckerTaskName}:
    post:
      operationId: updateWorkFlowCheckerTaskStatus
      parameters:
      - explode: false
        in: path
        name: workFlowExecutionId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: workFlowCheckerTaskName
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkFlowCheckerTaskRequestDTO'
        required: true
      responses:
        "403":
          description: Forbidden
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Succeeded
        "404":
          description: Not found
        "401":
          description: Unauthorized
      summary: Updates a workflow checker task status
      tags:
      - Workflow
      x-contentType: application/json
      x-accepts: application/json
  /api/v1/projects:
    get:
      operationId: getProjects
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ProjectResponseDTO'
                type: array
          description: Succeeded
        "403":
          description: Forbidden
        "401":
          description: Unauthorized
      summary: Returns a list of project
      tags:
      - Project
      x-accepts: application/json
    post:
      operationId: createProject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectRequestDTO'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponseDTO'
          description: Created
        "401":
          description: Unauthorized
      summary: Creates a new project
      tags:
      - Project
      x-contentType: application/json
      x-accepts: application/json
  /api/v1/workflows/{id}/status:
    get:
      operationId: getStatus
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkFlowStatusResponseDTO'
          description: Succeeded
        "403":
          description: Forbidden
        "401":
          description: Unauthorized
      summary: Returns a workflow status
      tags:
      - Workflow
      x-accepts: application/json
  /api/v1/workflowdefinitions:
    get:
      operationId: getWorkFlowDefinitions
      parameters:
      - explode: true
        in: query
        name: name
        required: false
        schema:
          type: string
        style: form
      responses:
        "403":
          description: Forbidden
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/WorkFlowDefinitionResponseDTO'
                type: array
          description: Succeeded
        "401":
          description: Unauthorized
      summary: Returns a list of workflow definition
      tags:
      - Workflow Definition
      x-accepts: application/json
  /api/v1/workflowdefinitions/{id}:
    get:
      operationId: getWorkFlowDefinitionById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "404":
          description: Not found
        "401":
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkFlowDefinitionResponseDTO'
          description: Succeeded
      summary: Returns information about a workflow definition by id
      tags:
      - Workflow Definition
      x-accepts: application/json
  /api/v1/projects/{id}:
    get:
      operationId: getProjectById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "404":
          description: Not found
        "401":
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponseDTO'
          description: Succeeded
      summary: Returns information about a specified project
      tags:
      - Project
      x-accepts: application/json
components:
  schemas:
    ArgumentRequestDTO:
      example:
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
      type: object
    WorkFlowRequestDTO:
      example:
        workFlowName: workFlowName
        works:
        - arguments:
          - value: value
            key: key
          - value: value
            key: key
          workName: workName
          type: type
        - arguments:
          - value: value
            key: key
          - value: value
            key: key
          workName: workName
          type: type
        arguments:
        - value: value
          key: key
        - value: value
          key: key
        projectId: projectId
      properties:
        projectId:
          type: string
        workFlowName:
          type: string
        arguments:
          items:
            $ref: '#/components/schemas/ArgumentRequestDTO'
          type: array
        works:
          items:
            $ref: '#/components/schemas/WorkRequestDTO'
          type: array
      type: object
    WorkRequestDTO:
      example:
        arguments:
        - value: value
          key: key
        - value: value
          key: key
        workName: workName
        type: type
      properties:
        workName:
          type: string
        arguments:
          items:
            $ref: '#/components/schemas/ArgumentRequestDTO'
          type: array
        type:
          type: string
      type: object
    WorkFlowOption:
      example:
        identifier: identifier
        workFlowName: workFlowName
        displayName: displayName
        description: description
        details:
        - details
        - details
      properties:
        identifier:
          type: string
        displayName:
          type: string
        description:
          type: string
        details:
          items:
            type: string
          type: array
        workFlowName:
          type: string
      type: object
    WorkFlowOptions:
      example:
        continuationOptions:
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
        upgradeOptions:
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
        newOptions:
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
        migrationOptions:
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
        otherOptions:
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
        - identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
        optionsAvailable: true
        currentVersion:
          identifier: identifier
          workFlowName: workFlowName
          displayName: displayName
          description: description
          details:
          - details
          - details
      properties:
        currentVersion:
          $ref: '#/components/schemas/WorkFlowOption'
        upgradeOptions:
          items:
            $ref: '#/components/schemas/WorkFlowOption'
          type: array
        migrationOptions:
          items:
            $ref: '#/components/schemas/WorkFlowOption'
          type: array
        newOptions:
          items:
            $ref: '#/components/schemas/WorkFlowOption'
          type: array
        continuationOptions:
          items:
            $ref: '#/components/schemas/WorkFlowOption'
          type: array
        otherOptions:
          items:
            $ref: '#/components/schemas/WorkFlowOption'
          type: array
        optionsAvailable:
          type: boolean
      type: object
    WorkFlowResponseDTO:
      example:
        workStatus: FAILED
        workFlowOptions:
          continuationOptions:
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
          upgradeOptions:
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
          newOptions:
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
          migrationOptions:
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
          otherOptions:
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
          - identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
          optionsAvailable: true
          currentVersion:
            identifier: identifier
            workFlowName: workFlowName
            displayName: displayName
            description: description
            details:
            - details
            - details
        workFlowExecutionId: workFlowExecutionId
      properties:
        workFlowExecutionId:
          type: string
        workFlowOptions:
          $ref: '#/components/schemas/WorkFlowOptions'
        workStatus:
          enum:
          - FAILED
          - COMPLETED
          type: string
      type: object
    WorkFlowCheckerTaskRequestDTO:
      example:
        status: FAILED
      properties:
        status:
          enum:
          - FAILED
          - COMPLETED
          - IN_PROGRESS
          type: string
      type: object
    ProjectRequestDTO:
      example:
        name: name
        description: description
      properties:
        name:
          type: string
        description:
          type: string
      type: object
    ProjectResponseDTO:
      example:
        modifyDate: 2000-01-23T04:56:07.000+00:00
        name: name
        description: description
        id: id
        createDate: 2000-01-23T04:56:07.000+00:00
        username: username
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        createDate:
          format: date-time
          type: string
        modifyDate:
          format: date-time
          type: string
        username:
          type: string
      type: object
    WorkFlowStatusResponseDTO:
      example:
        workFlowName: workFlowName
        works:
        - works:
          - null
          - null
          name: name
          type: TASK
          status: FAILED
        - works:
          - null
          - null
          name: name
          type: TASK
          status: FAILED
        workFlowExecutionId: workFlowExecutionId
      properties:
        workFlowExecutionId:
          type: string
        workFlowName:
          type: string
        works:
          items:
            $ref: '#/components/schemas/WorkStatusResponseDTO'
          type: array
      type: object
    WorkStatusResponseDTO:
      example:
        works:
        - null
        - null
        name: name
        type: TASK
        status: FAILED
      properties:
        name:
          type: string
        type:
          enum:
          - TASK
          - WORKFLOW
          type: string
        status:
          enum:
          - FAILED
          - COMPLETED
          - PENDING
          type: string
        works:
          items:
            $ref: '#/components/schemas/WorkStatusResponseDTO'
          type: array
      type: object
    WorkDefinitionResponseDTO:
      example:
        outputs:
        - EXCEPTION
        - EXCEPTION
        processingType: processingType
        works:
        - null
        - null
        author: author
        name: name
        workType: workType
        id: id
        parameters:
        - '{}'
        - '{}'
      properties:
        id:
          type: string
        name:
          type: string
        workType:
          type: string
        processingType:
          type: string
        author:
          type: string
        works:
          items:
            $ref: '#/components/schemas/WorkDefinitionResponseDTO'
          type: array
        parameters:
          items:
            type: object
          type: array
        outputs:
          items:
            enum:
            - EXCEPTION
            - HTTP2XX
            - NO_EXCEPTION
            - OTHER
            type: string
          type: array
      type: object
    WorkFlowDefinitionResponseDTO:
      example:
        processingType: processingType
        works:
        - outputs:
          - EXCEPTION
          - EXCEPTION
          processingType: processingType
          works:
          - null
          - null
          author: author
          name: name
          workType: workType
          id: id
          parameters:
          - '{}'
          - '{}'
        - outputs:
          - EXCEPTION
          - EXCEPTION
          processingType: processingType
          works:
          - null
          - null
          author: author
          name: name
          workType: workType
          id: id
          parameters:
          - '{}'
          - '{}'
        modifyDate: 2000-01-23T04:56:07.000+00:00
        author: author
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: type
        parameters:
        - description: description
          optional: true
          type: PASSWORD
          key: key
        - description: description
          optional: true
          type: PASSWORD
          key: key
        createDate: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          format: uuid
          type: string
        name:
          type: string
        type:
          type: string
        processingType:
          type: string
        author:
          type: string
        createDate:
          format: date-time
          type: string
        modifyDate:
          format: date-time
          type: string
        parameters:
          items:
            $ref: '#/components/schemas/WorkFlowTaskParameter'
          type: array
        works:
          items:
            $ref: '#/components/schemas/WorkDefinitionResponseDTO'
          type: array
      type: object
    WorkFlowTaskParameter:
      example:
        description: description
        optional: true
        type: PASSWORD
        key: key
      properties:
        key:
          type: string
        description:
          type: string
        optional:
          type: boolean
        type:
          enum:
          - PASSWORD
          - TEXT
          - EMAIL
          - DATE
          - NUMBER
          - URL
          type: string
      type: object

